[package]
name = "spacegame"
version = "0.1.0"
authors = ["ZigTag <GitHub>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coffee = { version = "0.4", features = ["vulkan"] }

[profile.dev]
opt-level = 2